AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    Description: Deployment environment (test,production)
    AllowedValues:
      - test
      - production
    Default: test
Resources:
  ApiGatewayRestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "snappin-api"
      Description: "API Gateway for snappin"
      FailOnWarnings: true

  ApiGatewayResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: "ApiGatewayRestApi"

  ApiGatewayMethodOptions:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "OPTIONS"
      ResourceId:
        Ref: "ApiGatewayResource"
      RestApiId:
        Ref: "ApiGatewayRestApi"
      Integration:
        Type: "MOCK"
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,ANY'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiGatewayMethodAny:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiGatewayAuthorizer
      HttpMethod: "ANY"
      ResourceId:
        Ref: "ApiGatewayResource"
      RestApiId:
        Ref: "ApiGatewayRestApi"
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        IntegrationHttpMethod: "ANY"
        Type: "HTTP_PROXY"
        RequestParameters:
          integration.request.path.proxy: "method.request.path.proxy"
        Uri: http://fargate-test-alb-710076141.us-east-1.elb.amazonaws.com/{proxy}
      MethodResponses:
        - StatusCode: "200"

  ApiGatewayAuthorizer:
    Type: "AWS::ApiGateway::Authorizer"
    Properties:
      Name: "CognitoAuthorizer"
      Type: "COGNITO_USER_POOLS"
      IdentitySource: "method.request.header.Authorization"
      RestApiId:
        Ref: "ApiGatewayRestApi"
      ProviderARNs:
        - !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/snappin-${Environment}-user-pool"

Outputs:
  ApiGatewayUrl:
    Description: "URL for the API Gateway"
    Value:
      Fn::Sub: "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/myresource"
