AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - test
      - demo
      - production
    Default: test
Resources:
  BucketEventsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: !Sub "cloud-atlas-${Environment}-bucket-events-topic"
      TopicName: !Sub "cloud-atlas-${Environment}-bucket-events-topic"

  BucketEventsTopicSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref BucketEventsTopic
      Protocol: lambda
      Endpoint: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cloud-atlas-${Environment}-message-handler

  BucketEventsTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics:
        - !Ref BucketEventsTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action: "SNS:Publish"
            Resource: !Ref BucketEventsTopic
            Condition:
              StringEquals:
                Aws:SourceAccount: !Sub "${AWS::AccountId}"
Outputs:
  BucketsEventsTopicName:
    Description: "The name of the cloud-atlas buckets events topic"
    Value: !GetAtt BucketEventsTopic.TopicName
    Export:
      Name: !Sub "cloud-atlas-${Environment}-bucket-events-name"
  BucketsEventsTopicArn:
    Description: "The ARN of the cloud-atlas buckets events topic"
    Value: !GetAtt BucketEventsTopic.TopicArn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-bucket-events-topic-arn"
