AWSTemplateFormatVersion: "2010-09-09"

Resources:
  SnappinECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "snappin-api"
      ImageTagMutability: MUTABLE

Outputs:
  RepositoryArn:
    Description: "The ARN of the ECR repository"
    Value: !GetAtt SnappinECRRepository.Arn
    Export:
      Name: "snappin-ecr-repository-arn"
  RepositoryURI:
    Description: "The URI of the ECR repository"
    Value: !GetAtt SnappinECRRepository.RepositoryUri
    Export:
      Name: snappin-ecr-repository-uri
