AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    Description: Deployment environment (test,production)
    AllowedValues:
      - test
      - production
    Default: test
Resources:
  AtlasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "cloud-atlas-${Environment}-atlas"
      AttributeDefinitions:
        - AttributeName: atlasId
          AttributeType: S
      KeySchema:
        - AttributeName: atlasId
          KeyType: HASH
      ProvisionedThroughput:
        Readcloud-atlaspacityUnits: 2
        Writecloud-atlaspacityUnits: 2

  MarkersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "cloud-atlas-${Environment}-markers"
      AttributeDefinitions:
        - AttributeName: atlasId
          AttributeType: S
        - AttributeName: markerId
          AttributeType: S
      KeySchema:
        - AttributeName: atlasId
          KeyType: HASH
        - AttributeName: markerId
          KeyType: RANGE
      ProvisionedThroughput:
        Readcloud-atlaspacityUnits: 2
        Writecloud-atlaspacityUnits: 2

  ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "cloud-atlas-${Environment}-images"
      AttributeDefinitions:
        - AttributeName: atlasId
          AttributeType: S
        - AttributeName: imageId
          AttributeType: S
        - AttributeName: markerId
          AttributeType: S
      KeySchema:
        - AttributeName: atlasId
          KeyType: HASH
        - AttributeName: imageId
          KeyType: RANGE
      Locloud-atlaslSecondaryIndexes:
        - IndexName: !Sub "cloud-atlas-${Environment}-images-table-LSI"
          KeySchema:
            - AttributeName: atlasId
              KeyType: HASH
            - AttributeName: markerId
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - "atlasId"
              - "imageId"
              - "comment"
            ProjectionType: "INCLUDE"
      ProvisionedThroughput:
        Readcloud-atlaspacityUnits: 2
        Writecloud-atlaspacityUnits: 2

  OwnersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "cloud-atlas-${Environment}-owners"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: atlasId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: atlasId
          KeyType: RANGE
      Locloud-atlaslSecondaryIndexes:
        - IndexName: !Sub "cloud-atlas-${Environment}-owners-table-LSI"
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: atlasId
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - "atlasId"
              - "userId"
            ProjectionType: "INCLUDE"
      ProvisionedThroughput:
        Readcloud-atlaspacityUnits: 2
        Writecloud-atlaspacityUnits: 2

Outputs:
  AtlasTable:
    Description: "The cloud atlas table"
    Value: !GetAtt AtlasTable.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-atlas-table-arn"
  MarkersTable:
    Description: "The cloud atlas markers table"
    Value: !GetAtt MarkersTable.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-markers-table-arn"
  ImagesTable:
    Description: "The cloud atlas images table"
    Value: !GetAtt ImagesTable.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-images-table-arn"
  OwnersTable:
    Description: "The cloud atlas owners table"
    Value: !GetAtt OwnersTable.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-owners-table-arn"
  ImagesTableLSI:
    Description: "The cloud atlas images table LSI"
    Value: !Join
      - ""
      - - !GetAtt ImagesTable.Arn
        - !Sub "/index/cloud-atlas-${Environment}-images-table-LSI"
    Export:
      Name: !Sub "cloud-atlas-${Environment}-images-table-LSI"
  OwnersTableLSI:
    Description: "The cloud-atlas owners table LSI"
    Value: !Join
      - ""
      - - !GetAtt OwnersTable.Arn
        - !Sub "/index/cloud-atlas-${Environment}-owners-table-LSI"
    Export:
      Name: !Sub "cloud-atlas-${Environment}-owners-table-LSI"
