AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - test
      - demo
      - production
    Default: test
Resources:
  OptimizedImagesQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Sub "cloud-atlas-${Environment}-optimized-images-queue"
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      DelaySeconds: 0
      MaximumMessageSize: 262144
      ReceiveMessageWaitTimeSeconds: 0
Outputs:
  QueueArn:
    Description: "The ARN of the SQS queue where messages related to optimized images being stored to S3 are placed"
    Value: !GetAtt OptimizedImagesQueue.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-optimized-images-queue-arn"
  QueueUrl:
    Description: "The URL of the SQS queue where messages related to optimized images being stored to S3 are placed"
    Value: !Ref OptimizedImagesQueue
    Export:
      Name: !Sub "cloud-atlas-${Environment}-optimized-images-queue-url"
