AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - test
      - demo
      - production
    Default: test
Resources:
  DumpBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "cloud-atlas-${Environment}-dump"
      AccessControl: Private
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:cloud-atlas-${Environment}-bucket-events-topic
            Event: "s3:ObjectCreated:*"
          - Topic: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:cloud-atlas-${Environment}-bucket-events-topic
            Event: "s3:ObjectRemoved:*"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - POST
            AllowedOrigins:
              - "*"
            MaxAge: 3600

  OptimizedBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "cloud-atlas-${Environment}-optimized"
      AccessControl: Private
      NotificationConfiguration:
        TopicConfigurations:
          - Event: "s3:ObjectCreated:*"
            Topic: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:cloud-atlas-${Environment}-bucket-events-topic

  LambdasBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "cloud-atlas-${Environment}-lambdas"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  DumpBucketArn:
    Description: "The ARN of the cloud-atlas dump bucket"
    Value: !GetAtt DumpBucket.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-dump-bucket-arn"
  OptimizedBucketArn:
    Description: "The ARN of the cloud-atlas optimized bucket"
    Value: !GetAtt OptimizedBucket.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-optimized-bucket-arn"
  LambdasBucketArn:
    Description: "The ARN of the cloud-atlas Lambda bucket"
    Value: !GetAtt LambdasBucket.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-lambdas-bucket-arn"
