AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - test
      - demo
      - production
    Default: test
  MessageHandlerLambdaS3ObjectVersion:
    Type: String
  ProcessImageLambdaS3ObjectVersion:
    Type: String
Resources:
  ProcessImageFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Sub "cloud-atlas-${Environment}-process-image"
      Handler: index.handler
      Role: !GetAtt ProcessImageRole.Arn
      Runtime: nodejs18.x
      Code:
        S3Bucket: !Sub "cloud-atlas-${Environment}-lambdas"
        S3Key: process-image.zip
        S3ObjectVersion: !Sub ${ProcessImageLambdaS3ObjectVersion}
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          NODE_ENV: !Sub ${Environment}
          LOCAL_ENDPOINT: placeholder
          DUMP_BUCKET_NAME: !Sub "cloud-atlas-${Environment}-dump"
          OPTIMIZED_BUCKET_NAME: !Sub "cloud-atlas-${Environment}-optimized"
      Tags:
        - Key: Name
          Value: !Sub "cloud-atlas-${Environment}-process-image"

  MessageHandlerFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Sub "cloud-atlas-${Environment}-message-handler"
      Handler: index.handler
      Role: !GetAtt MessageHandlerRole.Arn
      Runtime: nodejs18.x
      Code:
        S3Bucket: !Sub "cloud-atlas-${Environment}-lambdas"
        S3Key: message-handler.zip
        S3ObjectVersion: !Sub ${MessageHandlerLambdaS3ObjectVersion}
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          NODE_ENV: !Sub ${Environment}
          LOCAL_ENDPOINT: placeholder
          DUMP_BUCKET_NAME: !Sub "cloud-atlas-${Environment}-dump"
          OPTIMIZED_BUCKET_NAME: !Sub "cloud-atlas-${Environment}-optimized"
          PROCESS_IMAGE_FN_NAME: !Sub "cloud-atlas-${Environment}-process-image"
          QUEUE_URL: !Join
            - ""
            - - Fn::ImportValue: !Sub "cloud-atlas-${Environment}-optimized-images-queue-url"
      Tags:
        - Key: Name
          Value: !Sub "cloud-atlas-${Environment}-message-handler"

  MessageHandlerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MessageHandlerFunction
      Principal: sns.amazonaws.com
      SourceArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:cloud-atlas-${Environment}-bucket-events-topic

  ProcessImageRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub cloud-atlas-${Environment}-process-image-lambda-ReadFromDump
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource: !Sub "arn:aws:s3:::cloud-atlas-${Environment}-dump/*"
        - PolicyName: !Sub cloud-atlas-${Environment}-process-image-lambda-WriteToOptimized
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::cloud-atlas-${Environment}-optimized/*"

  MessageHandlerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt ProcessImageFunction.Arn
        - PolicyName: SQSSendMessagePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !Join
                  - ""
                  - - Fn::ImportValue: !Sub "cloud-atlas-${Environment}-optimized-images-queue-arn"
        - PolicyName: removeFromOptimizedBucketRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                Resource: !Sub "arn:aws:s3:::cloud-atlas-${Environment}-optimized/*"

Outputs:
  ProcessImageFnArn:
    Description: "The ARN of the cloud-atlas process image fn"
    Value: !GetAtt ProcessImageFunction.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-process-image-lambda-arn"
  ProcessImageFnRoleArn:
    Description: "The ARN of the cloud-atlas process image fn role"
    Value: !GetAtt ProcessImageRole.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-process-image-lambda-role-arn"
  MessageHandlerFnArn:
    Description: "The ARN of the cloud-atlas message handler fn"
    Value: !GetAtt MessageHandlerFunction.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-message-handler-lambda-arn"
  MessageHandlerFnRoleArn:
    Description: "The ARN of the cloud-atlas message handler fn role"
    Value: !GetAtt MessageHandlerFunction.Arn
    Export:
      Name: !Sub "cloud-atlas-${Environment}-message-handler-lambda-role-arn"
