AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    Description: Deployment environment (test,production)
    AllowedValues:
      - test
      - production
    Default: test
Resources:
  ProcessImageFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Sub "snappin-${Environment}-process-image"
      Handler: index.handler
      Role: !GetAtt ProcessImageRole.Arn
      Runtime: nodejs18.x
      Code:
        S3Bucket: !Sub "snappin-${Environment}-lambdas"
        S3Key: process-image.zip
        S3ObjectVersion: x6pB6AJCy3tJpo2bTrK6BGoT9YOeV.1B
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          NODE_ENV: !Sub ${Environment}
          LOCAL_ENDPOINT: placeholder
          DUMP_BUCKET_NAME: !Sub "snappin-${Environment}-dump"
          OPTIMIZED_BUCKET_NAME: !Sub "snappin-${Environment}-optimized"
      Tags:
        - Key: Name
          Value: !Sub "snappin-${Environment}-process-image"

  MessageHandlerFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Sub "snappin-${Environment}-message-handler"
      Handler: index.handler
      Role: !GetAtt MessageHandlerRole.Arn
      Runtime: nodejs18.x
      Code:
        S3Bucket: !Sub "snappin-${Environment}-lambdas"
        S3Key: message-handler.zip
        S3ObjectVersion: XIvDyqXlA1eMU80ljyAttlRRwAXGT76d
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          NODE_ENV: !Sub ${Environment}
          LOCAL_ENDPOINT: placeholder
          DUMP_BUCKET_NAME: !Sub "snappin-${Environment}-dump"
          OPTIMIZED_BUCKET_NAME: !Sub "snappin-${Environment}-optimized"
          PROCESS_IMAGE_FN_NAME: !Sub "snappin-${Environment}-process-image"
          QUEUE_URL: !Join
            - ""
            - - Fn::ImportValue: !Sub "snappin-${Environment}-optimized-images-queue-url"

      Tags:
        - Key: Name
          Value: !Sub "snappin-${Environment}-message-handler"

  MessageHandlerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MessageHandlerFunction
      Principal: sns.amazonaws.com
      SourceArn: !Join
        - ""
        - - Fn::ImportValue: !Sub "snappin-${Environment}-bucket-events-topic-arn"

  ProcessImageRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub Snappin-${Environment}-process-image-lambda-ReadFromDump
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource: !Sub "arn:aws:s3:::snappin-${Environment}-dump/*"
        - PolicyName: !Sub Snappin-${Environment}-process-image-lambda-WriteToOptimized
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::snappin-${Environment}-optimized/*"

  MessageHandlerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
        - PolicyName: SQSSendMessagePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !Join
                  - ""
                  - - Fn::ImportValue: !Sub "snappin-${Environment}-optimized-images-queue-arn"
Outputs:
  ProcessImageFnArn:
    Description: "The ARN of the Snappin process image fn"
    Value: !GetAtt ProcessImageFunction.Arn
    Export:
      Name: !Sub "snappin-${Environment}-process-image-lambda-arn"
  ProcessImageFnRoleArn:
    Description: "The ARN of the Snappin process image fn role"
    Value: !GetAtt ProcessImageRole.Arn
    Export:
      Name: !Sub "snappin-${Environment}-process-image-lambda-role-arn"
  MessageHandlerFnArn:
    Description: "The ARN of the Snappin message handler fn"
    Value: !GetAtt MessageHandlerFunction.Arn
    Export:
      Name: !Sub "snappin-${Environment}-message-handler-lambda-arn"
  MessageHandlerFnRoleArn:
    Description: "The ARN of the Snappin message handler fn role"
    Value: !GetAtt MessageHandlerFunction.Arn
    Export:
      Name: !Sub "snappin-${Environment}-message-handler-lambda-role-arn"
