AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - test
      - demo
      - production
    Default: test
Resources:
  CloudfrontPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub cloud-atlas-${Environment}-cloudfront-private-key
      Description: The private key used by cloudfront to sign urls
Outputs:
  CloudfrontPrivateKeyArn:
    Description: "The ARN of the secret that contains the private key to sign cloudfront URLs"
    Value: !GetAtt CloudfrontPrivateKey.Id
    Export:
      Name: !Sub "cloud-atlas-${Environment}-cloudfront-private-key-arn"
  CloudfrontPrivateKeyName:
    Description: "The name of the secret that contains the private key to sign cloudfront URLs"
    Value: !Sub cloud-atlas-${Environment}-cloudfront-private-key
    Export:
      Name: !Sub "cloud-atlas-${Environment}-cloudfront-private-key-name"
